



spring:
  # data:
  #   mongodb:
  #     host: localhost
  #     port: 27017
  #     database: java-db

  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/java-db'
    username: postgres
    password: password
  jpa:
    properties.hibernate.show_sql: true
    properties.hibernate.use_sql_comments: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



logging.level.root: INFO
# logging.level.org.springframework.web: DEBUG
# logging.file.name: app.log
# logging.file.max-size: 10MB
# logging.file.max-history: 10
# logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
# logging.level.com.myapp.service: INFO